# Generated by Django 6.1.1 on 2026-09-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_exchangerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='exchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Pending')), fields=('sender', 'receiver'), name='unique_pending_exchange_request'),
        ),
        migrations.AddConstraint(
            model_name='exchangerequest',
            constraint=models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='prevent_self_exchange_request'),
        ),
    ]
